version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "09:00"
      timezone: Europe/Berlin
    assignees:
      - acim
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "09:00"
      timezone: Europe/Berlin
    assignees:
      - acim
    groups:
      dependencies:
        patterns:
          - "*"
