version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      - POSTGRES_DB=mig
      - POSTGRES_HOST_AUTH_METHOD=trust
  mig:
    build:
      context: .
    depends_on:
      - postgres
    stdin_open: true
    tty: true
