name: pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: raven-actions/actionlint@v2

  check:
    needs: actionlint
    uses: ectobit/reusable-workflows/.github/workflows/go-check.yaml@main
    with:
      lint-command: make lint

  test:
    needs: actionlint
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_DB: mig
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d mig"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - run: make test
